### ISSUE TITLE
2 bugs on the ListView sample

### ISSUE THREAD

**Issue by jcfevre** [ManuelPeinado/FadingActionBar#6]
On the listview sample :
 1- in landscape mode, the list go over the image when I'm scrolling down (see the attchemnt)

 2 - in portrait mode, When I'm at the top of the list (arriving on the screen) this is fine. But there is a light grey overlay that come from the bottom and overlays the list while I'm scrolling down.  ( see the attchemnt)

Tested on Galaxy S (the first one) with Cyanogen, android version 4.1.2

![landscape](https://f.cloud.github.com/assets/4689825/649013/505c45c4-d43b-11e2-87f4-49f8ab814f32.png)
![overlay](https://f.cloud.github.com/assets/4689825/649014/50780214-d43b-11e2-8a55-8330aa52f4a6.png)

**Comment by ManuelPeinado** [comment]
Hi, thanks for the heads-up!

Seems to be a problem with the parallax effect, can you check whether the "no parallax" demo works fine?

**Comment by jcfevre** [comment]
All others samples of your demo work fine, even with parallax effect. 
Only the ListView sample has this problem. 

I'll try tonight to remove the parallax effect in my application with the listView sample...

**Comment by ManuelPeinado** [comment]
I guess the other demos use ScrollViews instead of ListView, so this must
be a ListView problem only.

**Comment by ManuelPeinado** [comment]
This is broken for me, too. I'll provide a fix ASAP. Stay tuned

**Comment by ManuelPeinado** [comment]
Fixed in 2.2.0!!

Thanks again for reporting the issue.

**Comment by jcfevre** [comment]
Hi Manuel,

I'm sorry, but the bug still exists in the demo application (after updating
it).

If you don't reproduce the bug, could  switch  between portrait and
landscape mode on the listview sample ?

2013/6/22 ManuelPeinado notifications@github.com

> Fixed in 2.2.0!!
> 
> Thanks again for reporting the issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ManuelPeinado/FadingActionBar/issues/6#issuecomment-19852889
> .

## 

Jean-Charles

**Comment by jcfevre** [comment]
Here the steps to see the bug : 
- go to the listview sample
- switch your screen in lanscape mode
- scroll down to the end of the list
- scroll up to the top of the list
- scroll down slowly : here is the bug (the list go over the image )

The other bug (overlay) seems to be fixed.

Thanks

**Comment by ManuelPeinado** [comment]
That's weird, I thought I had solved both issues. Anyway, thanks a lot for
the heads up. I'll look into this as soon as I can.

**Comment by ManuelPeinado** [comment]
@jcfevre Just released v2.2.4 which I'm pretty sure fixes all ListView-related issues. Thanks again for your help!

**Comment by jcfevre** [comment]
Sorry, but... after updating application, I always have a problem in landscape mode with listview.

the behavior is slightly different, but the text is always cover image.

It's better, but not perfect...

**Comment by ManuelPeinado** [comment]
It works perfectly for me now, what device/version are are using for your tests? Thanks for helping out.

**Comment by jcfevre** [comment]
I'm using Smg Galaxy S III
Android 4.1.2

**Comment by slidese** [comment]
I'm having the same issue on a HTC One, 4.2.2.

Seems to be the parallax + ListView problem. Any ideas about what could be wrong?

**Comment by Nammari** [comment]
me too i have the same problem on Nexus 4.
parallex + ListView problem

**Comment by vickychijwani** [comment]
Same issue here, Nexus 4, Android 4.4.2. It happens in the ListView example if I first scroll down, then scroll back to the top, and then scroll down again.

**Comment by DanielNovak** [comment]
Same issues on 4.4.2 Motorola Moto G. Rotating the display will reproduce the issue. And this is more of a problem in case you have a fragment with this fading actionbar in the backstack and you return to it with the back button - the backround is always messed up.

**Comment by DanielNovak** [comment]
I think I found a clue what might be happening - the listview scroll position is persisted during orientation change, but the fading actionbar doesn't take this into account. I guess it assumes that it always starts from the top scroll position.

Setting listView.setSaveEnabled(false) will fix this, but the scroll state is lost during orientation change.

**Comment by AndroidDeveloperLB** [comment]
Is there another solution/workaround for this other than not-saving the listView's scroll state ?

**Comment by akash09766** [comment]
i am also facing same problem in my app which i have developed by using manuelPeinado/FadingActionBar library .
i think app problem is " the app using portrait mode layout parameters (height and all that ) in landscape mode."

**Comment by akash09766** [comment]
did anyone find solution . no parallax is also not working in my project
